-- INSERT INTO sales (
--         date_created,
--         date_fulfilled,
--         customer_name,
--         product_name,
--         volume
--     )
-- VALUES (
--         '2021-12-09',
--         '2021-12-17',
--         'Company Z',
--         'A Tuck',
--         109.0
--     );
-- update sales
-- set volume = volume * 1000
-- where customer_name = 'Company Z';